---
abstract: 'Perl module to extract fields from objects '
author:
  - 'Paul Boyd <pboyd@dev3l.net>'
build_requires:
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-FieldPath
requires:
  Hash::Merge: 0.11
  List::Util: 0
  Parse::RecDescent: 1.963
  Scalar::Util: 0
version: 0.001
